package net.lwenstrom.tft.backend.core.model;

public enum AugmentEffectType {
    TEAM_ATTACK_SPEED_PER_RANGED_UNIT,
    TEAM_DAMAGE_REDUCTION,
    TEAM_ATTACK_DAMAGE_ON_KILL,
    TEAM_MAX_HEALTH,
    TEAM_ATTACK_DAMAGE,
    TEAM_ABILITY_POWER,
    TEAM_ARMOR_AND_MAGIC_RESIST,
    MELEE_LIFESTEAL,
    RANGED_ATTACK_DAMAGE,
    TEAM_MANA_GAIN,
    TEAM_STARTING_MANA,
    GOLD_PER_EMPTY_BENCH_SLOT,
    TEAM_STARTING_SHIELD,
    GOLD,
    XP
}
